Fix (clang) linker issue cuased by missing 'static inline's
```
/usr/bin/ld: ./ndpi_bitmap.o: in function `roaring_trailing_zeroes':
/home/runner/work/nDPId/nDPId/libnDPI/src/lib/ndpi_bitmap.c:293: multiple definition of `roaring_trailing_zeroes';
third_party/src/roaring.o:/home/runner/work/nDPId/nDPId/libnDPI/src/lib/third_party/src/roaring.c:293: first defined here
```

Signed-off-by: Toni Uhlig <matzeton@googlemail.com>